### ISSUE TITLE
Update "Submission Processing Started" email subject title to include evaluation name

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowOrchestrator#18]
Is it possible to get the evaluation queue id name to be sent to the submitter in the "Submission processing started" email?  The email currently doesnt mention which evaluation queue people submitted to and I have a notification step in my workflow to do that.

The subject looks like:

```Submission to 'My Queue Name' received!```

**Comment by brucehoff** [comment]
@thomasyu888 are you sure this message is sent by the Orchestrator?  I don't see it in the code base.

**Comment by thomasyu888** [comment]
This message is not sent by the orchestrator. Current whats sent by the orchestrator subject is:

submission process started...

I'm suggesting that the orchestrator sends a more informative "workflow started" email.

**Comment by brucehoff** [comment]
@thomasyu888  I am confused.  In your initial post you say, "Is it possible to get the evaluation queue id name to be sent to the submitter in the 'Submission processing started' email?"  You then say, "This message is not sent by the orchestrator, it is sent by my workflow."  So wouldn't this be a change to your workflow, rather than to the Orchestrator?

**Comment by brucehoff** [comment]
Did you mean to ask, "Is it possible to get the evaluation queue id and name to be sent from the Orchestrator to the workflow so that the workflow can include this information is its 'Submission processing started' email?"

**Comment by thomasyu888** [comment]
@brucehoff, no let me explain. my apologies for the confusion.  Currently the orchestrator sends a workflow started email with the subject title `Submission Processing Started
`, and its contents:

```Dear Thomas Yu (thomas.yu):

Your submission (submission ID ...) is in progress.  Log files produced while your workflow is running will be periodically uploaded here: https://www.synapse.org/#!Synapse:syn.... Further notification will be provided when it is complete.

Sincerely,

Submission Queue Administration```

In this email, it doesn't tell the submitter which queue they submitted to, so if they submitted to 6 different queues, they would receive 6 of these emails with the same subject title, just with different submission ids. That being said, the submission id doesn't tell the submitter about where they had submitted to.

I am proposing that the orchestrator sends a workflow started email with the subject title `Submission to 'My Queue Name' processing`.  Currently, I have NOTIFICATION_MASK in the orchestrator set to **not** send the default orchestrator workflow started email, because I include the evaluation queue name in the notification email I send.   

The solution I stated at the end is also an acceptable workflow, I just thought adding the queue name would be a nice addition to the orchestrator submission processing started email template.

**Comment by brucehoff** [comment]
Yes, that makes sense.  Thanks for clarifying.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/commit/00e4bd2e8f3fea8744ee01d2fafe97a8c216e11e
