### ISSUE TITLE
Sometimes notification email contains link to logs, sometimes it doesnt

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowOrchestrator#19]
<img width="836" alt="Screen Shot 2020-02-10 at 9 58 32 AM" src="https://user-images.githubusercontent.com/10556275/74176121-ee8f7c00-4beb-11ea-9dba-7e6170cab572.png">

**Comment by brucehoff** [comment]
@thomasyu888, are you setting SHARE_RESULTS_IMMEDIATELY to false in the second case?  (I think you are not, but just want to be sure.)

**Comment by thomasyu888** [comment]
I am not. That line is commented out.

**Comment by brucehoff** [comment]
Done!

https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/commit/5f94e731c23edd612dc3f007a58fb97489a0a71d

**Comment by brucehoff** [comment]
(I updated both the 'master' branch and 'release-1.1'.)
