### ISSUE TITLE
The Orchestrator doesn't seem to exit when there is an error

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowOrchestrator#2]
After #1 happened, the hook seems to be stuck.  I have to control + C to force exit.

**Comment by thomasyu888** [comment]
This also happens with #4

**Comment by brucehoff** [comment]
@thomasyu888  I wonder how long you waited before interrupting with control + C.  When doing a 'docker pull' the Orchestrator will retry up to 10 times, just in case the problem was due to a transient network issue.  The next time it happens, would you wait a few minutes before interrupting?

**Comment by thomasyu888** [comment]
Closing for now, as I don't actually experience this any longer.
