### ISSUE TITLE
sagebionetworks/synapse-workflow-orchestrator-toil docker errors on build

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowOrchestrator#20]
https://hub.docker.com/repository/docker/sagebionetworks/synapse-workflow-orchestrator-toil/general

**Comment by thomasyu888** [comment]
I can't see the build details and logs to the repo, but Im sure if I could, maybe I could give a stab at fixing the issue.

**Comment by brucehoff** [comment]
The error is:
```
[91mERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
toil depends on http-parser@ https://github.com/adamnovak/http-parser/archive/190a17839ba229c635b59d960579451a81fe73f3.zip#sha256=3d30c84a426627e468657c44de199daee9d3210a48e392d4ad2e7497c5010949
```

**Comment by brucehoff** [comment]
@thomasyu888 I increased your permissions in DockerHub.  Can you see the build details now?

**Comment by brucehoff** [comment]
Back to normal: https://hub.docker.com/repository/docker/sagebionetworks/synapse-workflow-orchestrator-toil/builds

**Comment by thomasyu888** [comment]
Thanks @brucehoff and yes I can see the build details now.
