### ISSUE TITLE
Incorrectly grabs number of running workflows

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowOrchestrator#6]
The way that MAX_CONCURRENT_WORKFLOWS is implemented currently is incorrect.  Workflows of all types are listed by doing `wes-client --list`.    It looks something like this:
```
[
....,
        {
            "run_id": "c3a3cb0fc13b485eac4aa48b679785ed",
            "state": "EXECUTOR_ERROR"
        },
        {
            "run_id": "32e60f8c5def4e84acc554dce6dea73b",
            "state": "EXECUTOR_ERROR"
        },
        {
            "run_id": "67e3224ee04a4accbd8aa0a812c0be85",
            "state": "COMPLETE"
        }
    ]
```

It appears that you are just looking at all the listed workflows to check the workflows that are running.   I think you will have to look at the "state" of each run to determine the number of running workflows.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/commit/8274a5ce51ca3739bffbcbb7fe54db1d1c8b2f81
